### PR TITLE
Eliminate possible exception

### PR DESCRIPTION
**Pull request by sphinks**
https://github.com/fishtown-analytics/snowplow/issues/66

### CODE REVIEW

**Comment by drewbanin** [comment]
Thanks @sphinks! Just so I understand, can you clarify for me how this change addresses the issue that you raised in #66? Is the problem that you weren't previously using the `snowplow_web_timing_context` model, then you enabled it? I imagine that if the `snowplow_page_views` model was initially built with the web timing context enabled, then this wouldn't be a problem, right?

**Comment by sphinks** [comment]
@drewbanin data that is coming into `snowplow_page_view` for timing section is originally stored in bigint. However, we have a casting of null values to int, so in case there are null values (and it happens really often). It seems for me (I do not seem other possible place, where incoming bigint timing values for some reasons are casted into int in `snowplow_page_view`) that such casting of null values are causing narrowing of the whole column to int datatype. It works until we get really huge number (more than int4) in one of that column.

**Comment by drewbanin** [comment]
Ok, that sounds reasonable to me. This `default` implementation runs for:
 - Redshift
 - Postgres
 - Snowflake

Looks like each of these databases supports `bigint`, so I don't have any issue with merging this.

I will say though: this change probably won't help you directly, but it might help other users in a similar position. You'll still need to run a `--full-refresh` to get dbt to recreate your `snowplow_page_views` model with updated columns types.

Since the [affected code](https://github.com/fishtown-analytics/snowplow/blob/692938e572e3eca5cb019d2adf877f0d1b7f0147/macros/adapters/default/page_views/snowplow_page_views.sql#L285-L298) only runs when the timing context is disabled (that is: `var('snowplow:context:performance_timing')` is `False`), it doesn't sound to me like it will actually fix the problem that you currently have!

**Comment by sphinks** [comment]
@drewbanin you are correct. It won't help me, but that is the reason why I get to such situation:
1. Start with disabled performance_timing.
2. Table created with INT columns.
3. Some weeks later enable performance_timing.
4. Its values has to fit into existing table with INT columns.
5. It works, but sometimes can cause an error.

So the commit is to avoid such issue for new users.

**Comment by drewbanin** [comment]
alright! Thanks for your contribution :)

**Comment by drewbanin** [comment]
(released here: https://github.com/fishtown-analytics/snowplow/releases/tag/0.7.5)

**Comment by sphinks** [comment]
@drewbanin glad to make DBT a little bit better! :)

**Pull request merged**
