### PR TITLE
Feature: adapter model configs

### LINKED ISSUE #59: Use enabled config to implement cross-database support
Right now, Snowplow models are encoded as macros in order to implement cross-database support. Instead, we should experiment with making models specifically for each support adapter. I think broadly, this falls into:
- default (snowflake/redshift/postgres)
- bigquery

The models directory might look like:
```
models:
 - common/
 - default/
 - bigquery/
```

Every model would need to have a config like:
```
{{ config(enabled=(var('adapter') == 'default')) }}
or
{{ config(enabled=(var('adapter') == 'bigquery')) }}
```

I don't think we can configure this at a folder level in `dbt_project.yml`, but it might be worth exploring if there's some clever way to implement that.

The results of this experimentation might result is us wanting to _keep_ the adapter macro pattern, but I'm interested in exploring alternative ways of supporting cross-db model implementations in packages!

### PR DESCRIPTION
**Pull request by jtcohen6**
Fixes #59

Instead of relying on `adapter` macros, use model configs to enable/disable models based on `target.type`.

**The benefits:**
* We can store the majority of the code in the `models` folder, and avoid the need for "placeholder" model files.
* We can implement substantially different models on different targets, especially for intermediate transformations.

**The principle:**
* If we want a public function that can return the same output given the same input on any database, we should implement as an adapter macro.
* If we want to leverage database-specific functionality and be responsive to its modeling paradigm, we should implement as target-configured models.

TK is whether we should implement Snowflake in a manner more similar to Redshift or to BQ (nested events, fewer joins between models).

### CODE REVIEW

**Comment by drewbanin** [comment]
Nice looking PR @jtcohen6 - can you tell me how you felt while migrating/using this code? How does it stack up against the adapter macro pattern in your experience?

This generally LGTM. Is there any additional work remaining here, or is this good to go?

**Comment by jtcohen6** [comment]
@drewbanin Implemented an `enabled=is_adapter()` macro pattern as we discussed.

Would also really appreciate your eyes on the failing Circle tests! It seems to occur on 
```
Running setup.py install for googleapis-common-protos
```

**Comment by jtcohen6** [comment]
@drewbanin Just kidding, I realized that this branch's version of `.circleci/config.yml` was one commit (and one line) behind `master`. Merged, pushed, and all tests passed.

**Review by drewbanin — APPROVED** [review]
I didn't test this at all, but I love the concept and the code LGTM. If you feel good about this, then merge at will!

**Pull request merged**
